server:
  port: 8081
spring:
  application:
    name: card
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/card?createDatabaseIfNotExist=true
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  profiles:
    active: local
  config:
    import: "optional:configserver:http://localhost:8071/"

#  Disable RabbitMQ
#  rabbitmq:
#    host: "localhost"
#    port: 5672
#    username: "guest"
#    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"
