server:
  port: 8081
spring:
  application:
    name: card
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/card?createDatabaseIfNotExist=true
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true